using AnimStudio.Application.Transcripts.Parsing;
using AnimStudio.Domain.Transcripts;

namespace AnimStudio.Application.Tests.Transcripts;

public class SubtitleParserTests
{
    private static SubtitleParser NewParser() => new(new ParsingOptions());

    private const string SimpleVtt = """
        WEBVTT

        00:00:01.000 --> 00:00:04.000
        Hello there.

        00:00:05.000 --> 00:00:08.000
        General Kenobi.
        """;

    [Fact]
    public void Parses_a_basic_vtt_file()
    {
        var result = NewParser().Parse(SimpleVtt);

        Assert.Equal(SubtitleFormat.WebVtt, result.Format);
        Assert.Equal(TimingSource.Real, result.TimingSource);
        Assert.Equal(2, result.Cues.Count);
        Assert.Equal("Hello there.", result.Cues[0].Text);
        Assert.Equal(TimeSpan.FromSeconds(1), result.Cues[0].Start);
        Assert.Equal("General Kenobi.", result.Cues[1].Text);
    }

    [Fact]
    public void Survives_a_doubled_bom_and_crlf_line_endings()
    {
        // A file re-saved by some editors carries two BOMs, which breaks header detection
        // unless they are stripped in a loop.
        var awkward = "﻿﻿" + SimpleVtt.Replace("\n", "\r\n");

        var result = NewParser().Parse(awkward);

        Assert.Equal(SubtitleFormat.WebVtt, result.Format);
        Assert.Equal(2, result.Cues.Count);
        Assert.Equal("Hello there.", result.Cues[0].Text);
    }

    [Fact]
    public void Parses_subrip_with_sequence_numbers_and_comma_decimals()
    {
        var srt = """
            1
            00:00:01,000 --> 00:00:04,000
            First line.

            2
            00:00:05,000 --> 00:00:08,000
            Second line.
            """;

        var result = NewParser().Parse(srt);

        Assert.Equal(SubtitleFormat.SubRip, result.Format);
        Assert.Equal(2, result.Cues.Count);
        Assert.Equal("First line.", result.Cues[0].Text);
    }

    [Fact]
    public void Skips_note_style_and_region_blocks()
    {
        var vtt = """
            WEBVTT

            NOTE this is a comment
            that spans lines

            STYLE
            ::cue { color: peachpuff; }

            REGION
            id:fred

            00:00:01.000 --> 00:00:02.000
            Only real dialogue.
            """;

        var result = NewParser().Parse(vtt);

        Assert.Single(result.Cues);
        Assert.Equal("Only real dialogue.", result.Cues[0].Text);
    }

    [Fact]
    public void Extracts_voice_tag_speakers_and_strips_the_markup()
    {
        var vtt = """
            WEBVTT

            00:00:01.000 --> 00:00:04.000
            <v Roger>Where are we going?

            00:00:05.000 --> 00:00:08.000
            <v.loud Priya Sharma>To the park.</v>
            """;

        var result = NewParser().Parse(vtt);

        Assert.Equal("Roger", result.Cues[0].SpeakerLabel);
        Assert.Equal("Where are we going?", result.Cues[0].Text);
        // The ".loud" class must not leak into the speaker name.
        Assert.Equal("Priya Sharma", result.Cues[1].SpeakerLabel);
        Assert.Equal("To the park.", result.Cues[1].Text);
        Assert.Equal(SpeakerDetectionTier.VoiceTag, result.Cues[0].SpeakerTier);
    }

    [Fact]
    public void Strips_styling_tags_then_decodes_entities()
    {
        // Order matters: decoding first would turn "&lt;i&gt;" into a real tag and eat it.
        var vtt = """
            WEBVTT

            00:00:01.000 --> 00:00:04.000
            <c.colorE5E5E5><i>Tom</i></c> &amp; Jerry &lt;i&gt;stay&lt;/i&gt;
            """;

        var result = NewParser().Parse(vtt);

        Assert.Equal("Tom & Jerry <i>stay</i>", result.Cues[0].Text);
    }

    [Fact]
    public void Rebuilds_rolling_auto_captions_from_word_timestamps()
    {
        // YouTube auto-captions repeat the previous cue's tail. Naive parsing yields the
        // transcript two or three times over.
        var vtt = """
            WEBVTT

            00:00:00.000 --> 00:00:02.000
            <00:00:00.100><c>we</c><00:00:00.400><c> are</c><00:00:00.800><c> going</c>

            00:00:02.000 --> 00:00:04.000
            we are going
            <00:00:02.100><c>to</c><00:00:02.500><c> the</c><00:00:02.900><c> park.</c>
            """;

        var result = NewParser().Parse(vtt);

        Assert.True(result.IsAutoGenerated);
        var allText = string.Join(" ", result.Cues.Select(c => c.Text));
        // "we are going" must appear exactly once, not twice.
        Assert.Equal(1, CountOccurrences(allText, "we are going"));
        Assert.Contains("park.", allText);
    }

    [Fact]
    public void Deduplicates_rolling_captions_without_word_timestamps()
    {
        var vtt = """
            WEBVTT

            00:00:00.000 --> 00:00:02.000
            we are

            00:00:02.000 --> 00:00:04.000
            we are going

            00:00:04.000 --> 00:00:06.000
            we are going to the park
            """;

        var result = NewParser().Parse(vtt);

        Assert.True(result.IsAutoGenerated);
        var allText = string.Join(" ", result.Cues.Select(c => c.Text));
        Assert.Equal(1, CountOccurrences(allText, "we are"));
        Assert.Contains("park", allText);
    }

    [Fact]
    public void Drops_non_speech_cues_by_default_but_keeps_dialogue()
    {
        var vtt = """
            WEBVTT

            00:00:01.000 --> 00:00:02.000
            [MUSIC]

            00:00:02.000 --> 00:00:03.000
            (applause)

            00:00:03.000 --> 00:00:05.000
            Real dialogue here.
            """;

        var result = NewParser().Parse(vtt);

        Assert.Single(result.Cues);
        Assert.Equal("Real dialogue here.", result.Cues[0].Text);
    }

    [Fact]
    public void Repairs_a_cue_whose_end_is_not_after_its_start()
    {
        var vtt = """
            WEBVTT

            00:00:05.000 --> 00:00:05.000
            Zero length.
            """;

        var result = NewParser().Parse(vtt);

        Assert.Single(result.Cues);
        Assert.True(result.Cues[0].End > result.Cues[0].Start);
        // The raw timing is preserved so a normalization bug stays diagnosable.
        Assert.Equal(TimeSpan.FromSeconds(5), result.Cues[0].RawEnd);
    }

    [Fact]
    public void Keeps_overlapping_lines_from_different_speakers()
    {
        // Genuine crosstalk: never drop a speaker's line to tidy the timeline.
        var vtt = """
            WEBVTT

            00:00:01.000 --> 00:00:06.000
            <v Rahul>I was saying that

            00:00:03.000 --> 00:00:07.000
            <v Priya>Sorry to interrupt
            """;

        var result = NewParser().Parse(vtt);

        Assert.Equal(2, result.Cues.Count);
        Assert.Contains(result.Cues, c => c.IsOverlapping);
    }

    [Fact]
    public void Falls_back_to_synthesized_timings_for_plain_text()
    {
        var text = """
            Rahul: Let's go to the park.
            Priya: Good idea.
            """;

        var result = NewParser().Parse(text);

        Assert.Equal(SubtitleFormat.PlainText, result.Format);
        Assert.Equal(TimingSource.Synthesized, result.TimingSource);
        Assert.Equal(2, result.Cues.Count);
        // Estimated cues must still be ordered and contiguous.
        Assert.True(result.Cues[1].Start >= result.Cues[0].End);
        Assert.Contains(result.Warnings, w => w.Contains("estimated"));
    }

    [Fact]
    public void Rejects_input_with_no_usable_cues()
    {
        var ex = Assert.Throws<SubtitleParseException>(() =>
            NewParser().Parse("WEBVTT\n\n00:00:01.000 --> 00:00:02.000\n"));
        Assert.Equal("unparseable-subtitle", ex.Code);
    }

    [Fact]
    public void Rejects_a_transcript_over_the_character_cap()
    {
        var parser = new SubtitleParser(new ParsingOptions { MaxTranscriptCharacters = 100 });
        var ex = Assert.Throws<SubtitleParseException>(() => parser.Parse(new string('a', 200)));
        Assert.Equal("transcript-too-large", ex.Code);
    }

    private static int CountOccurrences(string haystack, string needle)
    {
        var count = 0;
        var at = 0;
        while ((at = haystack.IndexOf(needle, at, StringComparison.Ordinal)) >= 0) { count++; at += needle.Length; }
        return count;
    }
}
