using AnimStudio.Domain.Transcripts;

namespace AnimStudio.Domain.Ingest;

public enum IngestStatus { Pending = 0, Processing = 1, Completed = 2 , Failed = 3, Cancelled = 4 }

/// <summary>
/// A user's assertion that they have the right to use the source material, captured
/// per request and retained for audit. Without an identified attester an attestation
/// is worthless, so this always records who and when.
/// </summary>
public sealed class RightsAttestation
{
    public bool IsOwnerOrLicensed { get; set; }

    /// <summary>Closed set, so the field stays auditable and queryable: see RightsBasis.</summary>
    public string BasisCode { get; set; } = string.Empty;

    /// <summary>Free-text detail. Untrusted input and personal data - never logged.</summary>
    public string? BasisNotes { get; set; }

    public string? AttestedByUserId { get; set; }

    /// <summary>Personal data: excluded from list responses and never logged.</summary>
    public string? AttestedByName { get; set; }

    public string AcceptedTermsVersion { get; set; } = string.Empty;
    public DateTime AttestedAtUtc { get; set; }

    /// <summary>
    /// What the system's policy actually was at the time. Without this snapshot,
    /// "media download was disabled back then" is unfalsifiable.
    /// </summary>
    public bool ConfigAllowMediaDownload { get; set; }
    public bool ConfigYtDlpEnabled { get; set; }
    public bool IncludeMediaRequested { get; set; }
    public string? AppVersion { get; set; }
}

public static class RightsBasis
{
    public const string IOwnTheContent = "IOwnTheContent";
    public const string WrittenPermission = "WrittenPermission";
    public const string PublicDomain = "PublicDomain";
    public const string OpenLicense = "OpenLicense";
    public const string OtherLawfulBasis = "OtherLawfulBasis";

    public static readonly string[] All =
        [IOwnTheContent, WrittenPermission, PublicDomain, OpenLicense, OtherLawfulBasis];

    public static bool IsValid(string? code) =>
        code is not null && Array.IndexOf(All, code) >= 0;
}

public sealed class TranscriptIngest
{
    public string Id { get; set; } = string.Empty;
    public string ProjectId { get; set; } = string.Empty;
    public string UserId { get; set; } = string.Empty;
    public IngestStatus Status { get; set; } = IngestStatus.Pending;
    public TranscriptSourceKind SourceKind { get; set; }

    public string? IdempotencyKey { get; set; }

    // Canonical URL only: rebuilt from a validated video id, never the raw user string.
    public string? SourceUrlNormalized { get; set; }
    public string? SourceUrlHash { get; set; }
    public string? SourceVideoId { get; set; }
    public string? SourceChannelKey { get; set; }
    public string? SourceTitle { get; set; }

    /// <summary>True when only captions were fetched - the default for URL ingest.</summary>
    public bool CaptionsOnly { get; set; } = true;
    public bool MediaDownloaded { get; set; }
    public string? MediaAssetId { get; set; }

    public string? CaptionLanguage { get; set; }
    public bool CaptionIsAutoGenerated { get; set; }

    public string? RawArtifactObjectKey { get; set; }
    public string? RawArtifactSha256 { get; set; }

    public int CueCount { get; set; }
    public string? ScriptId { get; set; }
    public string? ContentHash { get; set; }
    public TimingSource TimingSource { get; set; }

    public RightsAttestation? RightsAttestation { get; set; }

    public string? ToolName { get; set; }
    public string? ToolVersion { get; set; }

    public List<string> Warnings { get; set; } = [];
    public string? ErrorCode { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime? CompletedAt { get; set; }
}
