using System.Globalization;
using System.Text;
using AnimStudio.Application.Abstractions.Rendering;

namespace AnimStudio.Infrastructure.Subtitles;

/// <summary>
/// Writes an ASS subtitle file for one scene.
/// <para>
/// ASS is preferred over drawtext for several reasons, but two decide it. drawtext cannot
/// word-wrap at all, so wrapping would have to be computed in C# without font metrics.
/// And drawtext puts dialogue text INTO the filtergraph, where a colon, comma or percent
/// sign in a transcript can rewrite the graph - a filtergraph injection driven by
/// untrusted input. ASS keeps text in a data file that ffmpeg never parses as arguments,
/// needs one filter instead of one per line, and gives per-character styling for free.
/// </para>
/// </summary>
public sealed class AssSubtitleWriter : ISubtitleWriter
{
    private const string DefaultStyleName = "Default";

    public string Write(SubtitleRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);

        var builder = new StringBuilder();
        var font = AssTextSanitizer.SanitizeStyleName(request.FontName) == "Default"
            ? request.FontName
            : request.FontName;

        builder.Append(Header(request));
        builder.Append(Styles(request, font));
        builder.Append(Events(request));

        return builder.ToString();
    }

    private static string Header(SubtitleRequest request) =>
        // PlayResX/Y must match the canvas or libass scales the fonts unexpectedly.
        // ScaledBorderAndShadow keeps outlines proportional at any resolution.
        $"""
        [Script Info]
        ; Generated by AnimStudio AI - do not edit by hand
        ScriptType: v4.00+
        WrapStyle: 0
        ScaledBorderAndShadow: yes
        PlayResX: {request.Canvas.Width}
        PlayResY: {request.Canvas.Height}
        YCbCr Matrix: TV.709


        """;

    private static string Styles(SubtitleRequest request, string font)
    {
        var builder = new StringBuilder();
        builder.AppendLine("[V4+ Styles]");
        builder.AppendLine(
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
            + "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
            + "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding");

        builder.AppendLine(StyleRow(DefaultStyleName, font, request.FontSize, AssColor.White, bold: false));

        foreach (var (_, style) in request.StylesByCharacterId)
        {
            var name = AssTextSanitizer.SanitizeStyleName(style.Name);
            if (string.Equals(name, DefaultStyleName, StringComparison.Ordinal)) continue;

            builder.AppendLine(StyleRow(
                name, font, request.FontSize,
                AssColor.FromHex(style.ColorHex, AssColor.White),
                style.Bold));
        }

        builder.AppendLine();
        return builder.ToString();
    }

    private static string StyleRow(string name, string font, int size, string primary, bool bold) =>
        string.Create(CultureInfo.InvariantCulture,
            // Bold is -1 for on and 0 for off in ASS, not 1.
            $"Style: {name},{font},{size},{primary},&H000000FF,{AssColor.NearBlack},"
            + $"{AssColor.SemiTransparentBlack},{(bold ? -1 : 0)},0,0,0,100,100,0,0,1,3.5,1.5,2,120,120,64,1");

    private static string Events(SubtitleRequest request)
    {
        var builder = new StringBuilder();
        builder.AppendLine("[Events]");
        builder.AppendLine(
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text");

        var rate = request.Canvas.FrameRate;

        foreach (var line in request.Lines.OrderBy(l => l.RelativeStartFrame))
        {
            var text = AssTextSanitizer.Sanitize(line.Text);
            if (text.Length == 0) continue;

            var styleName = DefaultStyleName;
            if (line.SpeakerCharacterId is { } characterId
                && request.StylesByCharacterId.TryGetValue(characterId, out var style))
            {
                styleName = AssTextSanitizer.SanitizeStyleName(style.Name);
            }

            var start = AssTimecode.Format(new Domain.Rendering.FrameCount(line.RelativeStartFrame).ToTimeSpan(rate));
            var end = AssTimecode.Format(new Domain.Rendering.FrameCount(line.RelativeEndFrame).ToTimeSpan(rate));
            var speaker = AssTextSanitizer.SanitizeStyleName(line.SpeakerLabel);

            // Text is the final field and absorbs the rest of the line, so a comma in the
            // dialogue needs no escaping here.
            builder.AppendLine($"Dialogue: 0,{start},{end},{styleName},{speaker},0,0,0,,{text}");
        }

        return builder.ToString();
    }
}
