using AnimStudio.Domain.Transcripts;

namespace AnimStudio.Application.Abstractions.Transcripts;

public sealed record TranscriptSourceAvailability(
    bool IsAvailable, string? UnavailableReasonCode = null, string? ToolVersion = null,
    bool RequiresAttestation = false);

public sealed record TranscriptFetchRequest
{
    public required string IngestId { get; init; }
    public required string ProjectId { get; init; }
    public required TranscriptSourceKind Kind { get; init; }

    /// <summary>Pasted transcript text.</summary>
    public string? RawText { get; init; }

    /// <summary>Server-composed storage key for an uploaded subtitle or media file.</summary>
    public string? ArtifactObjectKey { get; init; }

    /// <summary>
    /// The REBUILT canonical URL, never the user's raw string - see YouTubeUrlValidator.
    /// </summary>
    public Uri? CanonicalUrl { get; init; }

    public IReadOnlyList<string> LanguagePreference { get; init; } = [];

    /// <summary>Honoured only when configuration also allows a media download.</summary>
    public bool IncludeMedia { get; init; }
}

public sealed record TranscriptFetchResult
{
    public required IReadOnlyList<TranscriptCue> Cues { get; init; }
    public required TimingSource TimingSource { get; init; }
    public string? Language { get; init; }
    public bool IsAutoGenerated { get; init; }

    public string? RawArtifactObjectKey { get; init; }
    public string? RawArtifactSha256 { get; init; }

    public string? SourceVideoId { get; init; }
    public string? SourceChannelKey { get; init; }
    public string? SourceTitle { get; init; }

    /// <summary>Null unless a media download or upload actually happened.</summary>
    public string? MediaObjectKey { get; init; }

    public IReadOnlyList<string> Warnings { get; init; } = [];
    public string? ToolName { get; init; }
    public string? ToolVersion { get; init; }
}

/// <summary>
/// One way of obtaining a transcript. Two of the implementations (pasted text and an
/// uploaded subtitle file) have no external dependency at all, so a fresh checkout with no
/// yt-dlp and no network still delivers the whole feature.
/// </summary>
public interface ITranscriptSource
{
    TranscriptSourceKind Kind { get; }

    /// <summary>
    /// Cheap, side-effect-free check. Drives the capabilities endpoint so the UI can
    /// disable what this server has not been configured for, instead of offering an option
    /// that fails on submit.
    /// </summary>
    Task<TranscriptSourceAvailability> ProbeAsync(CancellationToken ct);

    Task<TranscriptFetchResult> FetchAsync(TranscriptFetchRequest request, CancellationToken ct);
}

/// <summary>Raised when a transcript cannot be obtained. The code is what the API returns.</summary>
public sealed class TranscriptIngestException(string code, string message) : Exception(message)
{
    public string Code { get; } = code;
}
