/** Mirrors the backend's single response envelope. */
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  message?: string;
  errors: ApiError[];
}

export interface ApiError {
  code: string;
  message: string;
  field?: string;
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  status: string;
  width: number;
  height: number;
  fps: number;
  distributionIntent: string;
  acceptShareAlikeObligation: boolean;
  backgroundMusicAssetId?: string;
  backgroundMusicVolume: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateProjectBody {
  name: string;
  description?: string;
  width: number;
  height: number;
  fps: number;
  distributionIntent: string;
}

export interface UpdateProjectBody extends CreateProjectBody {
  acceptShareAlikeObligation: boolean;
  backgroundMusicAssetId?: string | null;
  backgroundMusicVolume: number;
}

export interface Asset {
  id: string;
  name: string;
  kind: string;
  mimeType: string;
  fileSizeBytes: number;
  width?: number;
  height?: number;
  hasAlpha: boolean;
  durationSeconds?: number;
  reviewStatus: string;
}

export interface CharacterAppearance {
  age?: number;
  gender?: string;
  hair?: string;
  clothes?: string;
  additionalDetails?: string;
}

export interface Character {
  id: string;
  name: string;
  description?: string;
  aliases: string[];
  closedMouthAssetId?: string;
  openMouthAssetId?: string;
  isNarrator: boolean;
  subtitleColorHex?: string;
  appearance: CharacterAppearance;
}

export interface CharacterBody {
  name: string;
  /** Null clears the value; undefined and null are both accepted by the API. */
  description?: string | null;
  aliases: string[];
  closedMouthAssetId?: string | null;
  openMouthAssetId?: string | null;
  subtitleColorHex?: string | null;
  appearance?: CharacterAppearance;
}

export interface IngestResult {
  ingestId: string;
  scriptId?: string;
  cueCount: number;
  segmentCount: number;
  timingSource: string;
  hasSourceTimings: boolean;
  warnings: string[];
}

export interface ScriptSummary {
  id: string;
  ingestId: string;
  version: number;
  status: string;
  timingSource: string;
  hasSourceTimings: boolean;
  segmentCount: number;
  lineCount: number;
  totalSeconds: number;
  warnings: string[];
  createdAt: string;
}

export interface ScriptLine {
  speakerLabel?: string;
  text: string;
  startSeconds: number;
  endSeconds: number;
}

export interface ScriptSegment {
  order: number;
  segmentKey: string;
  title?: string;
  dominantSpeakerLabel?: string;
  sourceStartSeconds: number;
  sourceEndSeconds: number;
  timelineStartSeconds: number;
  timelineEndSeconds: number;
  breakReason: string;
  lines: ScriptLine[];
}

export interface ScriptDetail extends ScriptSummary {
  projectId: string;
  segments: ScriptSegment[];
  segmentsTruncated: boolean;
}

export interface IngestSummary {
  id: string;
  source: string;
  status: string;
  scriptId?: string;
  cueCount: number;
  timingSource: string;
  sourceTitle?: string;
  captionLanguage?: string;
  captionIsAutoGenerated: boolean;
  captionsOnly: boolean;
  rightsBasisCode?: string;
  toolName?: string;
  toolVersion?: string;
  warnings: string[];
  errorCode?: string;
  createdAt: string;
  completedAt?: string;
}

export interface SceneGenerationResult {
  scenesCreated: number;
  scenesPreserved: number;
  unresolvedSpeakers: string[];
  warnings: string[];
}

/** A scene as it appears in the list. */
export interface Scene {
  id: string;
  sceneNumber: number;
  title?: string;
  durationFrames: number;
  durationSeconds: number;
  backgroundAssetId?: string;
  dialogueLines: number;
  transition: string;
  backgroundEffect: string;
  transitionDurationSeconds: number;
  audioAssetId?: string;
  hasAudioSlice: boolean;
  characterCount: number;
  origin: string;
  isUserEdited: boolean;
}

export interface DialogueLine {
  index: number;
  speakerCharacterId?: string;
  speakerLabel?: string;
  text: string;
  startSeconds: number;
  endSeconds: number;
}

export interface CharacterPlacement {
  characterId: string;
  anchor: string;
  heightFraction: number;
  offsetXFraction: number;
  offsetYFraction: number;
  flipHorizontal: boolean;
  zOrder: number;
  entrance: string;
  entranceDurationSeconds: number;
  presenceStartSeconds: number;
  presenceEndSeconds: number;
}

/** Everything the scene editor needs to draw its form. */
export interface SceneDetail {
  id: string;
  projectId: string;
  sceneNumber: number;
  title?: string;
  description?: string;
  durationFrames: number;
  durationSeconds: number;
  backgroundAssetId?: string;
  backgroundEffect: string;
  intensity: number;
  easing: string;
  fadeInSeconds: number;
  fadeOutSeconds: number;
  transition: string;
  transitionDurationSeconds: number;
  audioAssetId?: string;
  audioSliceStartSeconds?: number;
  audioSliceEndSeconds?: number;
  dialogue: DialogueLine[];
  characters: CharacterPlacement[];
  origin: string;
  isUserEdited: boolean;
  updatedAt: string;
}

export interface CreateSceneBody {
  title?: string;
  description?: string;
  durationSeconds: number;
  backgroundAssetId?: string;
  afterSceneId?: string;
}

export interface UpdateSceneBody {
  title?: string;
  description?: string;
  durationSeconds: number;
  backgroundEffect: string;
  intensity: number;
  easing: string;
  fadeInSeconds: number;
  fadeOutSeconds: number;
  transition: string;
  transitionDurationSeconds: number;
}

export interface DialogueBody {
  speakerCharacterId?: string | null;
  text: string;
  startSeconds: number;
  endSeconds: number;
}

export interface PlacementBody {
  characterId: string;
  anchor: string;
  heightFraction: number;
  offsetXFraction: number;
  offsetYFraction: number;
  flipHorizontal: boolean;
  zOrder: number;
  entrance: string;
  entranceDurationSeconds: number;
  presenceStartSeconds?: number | null;
  presenceEndSeconds?: number | null;
}

export interface SceneAudioBody {
  assetId?: string | null;
  sliceStartSeconds?: number | null;
  sliceEndSeconds?: number | null;
}

export interface RenderJob {
  jobId: string;
  projectId: string;
  status: string;
  progress: number;
  message?: string;
  currentStage: string;
  scenesTotal: number;
  scenesDone: number;
  errorCode?: string;
  errorMessage?: string;
  warnings: string[];
  hasOutput: boolean;
  outputDurationSeconds?: number;
  createdAt: string;
  completedAt?: string;
}

export interface RendererStatus {
  available: boolean;
  version?: string;
  unavailableReason?: string;
  burnedSubtitles: boolean;
  kenBurns: boolean;
  transitions: boolean;
}

export interface TranscriptSourceStatus {
  kind: string;
  available: boolean;
  unavailableReason?: string;
  toolVersion?: string;
  requiresAttestation: boolean;
}

export interface IngestCapabilities {
  defaultSource: string;
  mediaDownloadAllowed: boolean;
  sources: TranscriptSourceStatus[];
}

/** Terminal statuses; polling stops on any of these. */
export const TERMINAL_JOB_STATUSES = [
  'Completed',
  'CompletedWithWarnings',
  'Failed',
  'Cancelled',
] as const;

export function isTerminal(status: string): boolean {
  return (TERMINAL_JOB_STATUSES as readonly string[]).includes(status);
}

// --- option lists, kept beside the models so a select and its API value cannot drift ---

export const BACKGROUND_EFFECTS = [
  'None', 'ZoomIn', 'ZoomOut', 'PanLeft', 'PanRight', 'PanUp', 'PanDown',
] as const;

export const EASINGS = ['Linear', 'EaseInOut'] as const;

export const TRANSITIONS = [
  'None', 'Fade', 'Dissolve', 'WipeLeft', 'WipeRight',
  'SlideLeft', 'SlideRight', 'CircleOpen', 'CircleClose',
] as const;

export const ANCHORS = [
  'BottomLeft', 'BottomCenter', 'BottomRight', 'Center', 'CenterLeft', 'CenterRight',
] as const;

export const ENTRANCES = [
  'None', 'FadeIn', 'SlideFromLeft', 'SlideFromRight', 'SlideFromBottom',
] as const;

export const DISTRIBUTION_INTENTS = ['Personal', 'Public', 'Monetized'] as const;

/** Canvas presets, so the common shapes need no arithmetic from the user. */
export const CANVAS_PRESETS = [
  { label: 'Landscape 1080p', width: 1920, height: 1080 },
  { label: 'Landscape 720p', width: 1280, height: 720 },
  { label: 'Vertical 1080x1920', width: 1080, height: 1920 },
  { label: 'Square 1080', width: 1080, height: 1080 },
] as const;
