/** Mirrors the backend's single response envelope. */
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  message?: string;
  errors: ApiError[];
}

export interface ApiError {
  code: string;
  message: string;
  field?: string;
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  status: string;
  width: number;
  height: number;
  fps: number;
  distributionIntent: string;
  acceptShareAlikeObligation: boolean;
  backgroundMusicAssetId?: string;
  backgroundMusicVolume: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateProjectBody {
  name: string;
  description?: string;
  width: number;
  height: number;
  fps: number;
  distributionIntent: string;
}

export interface UpdateProjectBody extends CreateProjectBody {
  acceptShareAlikeObligation: boolean;
  backgroundMusicAssetId?: string | null;
  backgroundMusicVolume: number;
}

export interface Asset {
  id: string;
  name: string;
  kind: string;
  mimeType: string;
  fileSizeBytes: number;
  width?: number;
  height?: number;
  hasAlpha: boolean;
  durationSeconds?: number;
  reviewStatus: string;
}

export interface CharacterAppearance {
  age?: number;
  gender?: string;
  hair?: string;
  clothes?: string;
  additionalDetails?: string;
}

export interface Character {
  id: string;
  name: string;
  description?: string;
  aliases: string[];
  closedMouthAssetId?: string;
  openMouthAssetId?: string;
  isNarrator: boolean;
  subtitleColorHex?: string;
  appearance: CharacterAppearance;
}

export interface CharacterBody {
  name: string;
  /** Null clears the value; undefined and null are both accepted by the API. */
  description?: string | null;
  aliases: string[];
  closedMouthAssetId?: string | null;
  openMouthAssetId?: string | null;
  subtitleColorHex?: string | null;
  appearance?: CharacterAppearance;
}

export interface IngestResult {
  ingestId: string;
  scriptId?: string;
  cueCount: number;
  segmentCount: number;
  timingSource: string;
  hasSourceTimings: boolean;
  warnings: string[];
}

export interface ScriptSummary {
  id: string;
  ingestId: string;
  version: number;
  status: string;
  timingSource: string;
  hasSourceTimings: boolean;
  segmentCount: number;
  lineCount: number;
  totalSeconds: number;
  warnings: string[];
  createdAt: string;
}

export interface ScriptLine {
  speakerLabel?: string;
  text: string;
  startSeconds: number;
  endSeconds: number;
}

export interface ScriptSegment {
  order: number;
  segmentKey: string;
  title?: string;
  dominantSpeakerLabel?: string;
  sourceStartSeconds: number;
  sourceEndSeconds: number;
  timelineStartSeconds: number;
  timelineEndSeconds: number;
  breakReason: string;
  lines: ScriptLine[];
}

export interface ScriptDetail extends ScriptSummary {
  projectId: string;
  /** Project or ClipMerge, so a screen can say "clip 2 of 6" rather than "scene 2 of 6". */
  kind: string;
  segments: ScriptSegment[];
  segmentsTruncated: boolean;
}

export interface IngestSummary {
  id: string;
  source: string;
  status: string;
  scriptId?: string;
  cueCount: number;
  timingSource: string;
  sourceTitle?: string;
  captionLanguage?: string;
  captionIsAutoGenerated: boolean;
  captionsOnly: boolean;
  rightsBasisCode?: string;
  toolName?: string;
  toolVersion?: string;
  warnings: string[];
  errorCode?: string;
  createdAt: string;
  completedAt?: string;
}

export interface SceneGenerationResult {
  scenesCreated: number;
  scenesPreserved: number;
  unresolvedSpeakers: string[];
  warnings: string[];
}

/** A scene as it appears in the list. */
export interface Scene {
  id: string;
  sceneNumber: number;
  title?: string;
  durationFrames: number;
  durationSeconds: number;
  backgroundAssetId?: string;
  dialogueLines: number;
  transition: string;
  backgroundEffect: string;
  transitionDurationSeconds: number;
  audioAssetId?: string;
  hasAudioSlice: boolean;
  characterCount: number;
  origin: string;
  isUserEdited: boolean;
}

export interface DialogueLine {
  index: number;
  speakerCharacterId?: string;
  speakerLabel?: string;
  text: string;
  startSeconds: number;
  endSeconds: number;
}

export interface CharacterPlacement {
  characterId: string;
  anchor: string;
  heightFraction: number;
  offsetXFraction: number;
  offsetYFraction: number;
  flipHorizontal: boolean;
  zOrder: number;
  entrance: string;
  entranceDurationSeconds: number;
  presenceStartSeconds: number;
  presenceEndSeconds: number;
}

/** Everything the scene editor needs to draw its form. */
export interface SceneDetail {
  id: string;
  projectId: string;
  /** Project or ClipMerge, so a screen can say "clip 2 of 6" rather than "scene 2 of 6". */
  kind: string;
  sceneNumber: number;
  title?: string;
  description?: string;
  durationFrames: number;
  durationSeconds: number;
  backgroundAssetId?: string;
  backgroundEffect: string;
  intensity: number;
  easing: string;
  fadeInSeconds: number;
  fadeOutSeconds: number;
  transition: string;
  transitionDurationSeconds: number;
  audioAssetId?: string;
  audioSliceStartSeconds?: number;
  audioSliceEndSeconds?: number;
  dialogue: DialogueLine[];
  characters: CharacterPlacement[];
  origin: string;
  isUserEdited: boolean;
  updatedAt: string;
}

export interface CreateSceneBody {
  title?: string;
  description?: string;
  durationSeconds: number;
  backgroundAssetId?: string;
  afterSceneId?: string;
}

export interface UpdateSceneBody {
  title?: string;
  description?: string;
  durationSeconds: number;
  backgroundEffect: string;
  intensity: number;
  easing: string;
  fadeInSeconds: number;
  fadeOutSeconds: number;
  transition: string;
  transitionDurationSeconds: number;
}

export interface DialogueBody {
  speakerCharacterId?: string | null;
  text: string;
  startSeconds: number;
  endSeconds: number;
}

export interface PlacementBody {
  characterId: string;
  anchor: string;
  heightFraction: number;
  offsetXFraction: number;
  offsetYFraction: number;
  flipHorizontal: boolean;
  zOrder: number;
  entrance: string;
  entranceDurationSeconds: number;
  presenceStartSeconds?: number | null;
  presenceEndSeconds?: number | null;
}

export interface SceneAudioBody {
  assetId?: string | null;
  sliceStartSeconds?: number | null;
  sliceEndSeconds?: number | null;
}

export interface RenderJob {
  jobId: string;
  projectId: string;
  /** Project or ClipMerge, so a screen can say "clip 2 of 6" instead of "scene 2 of 6". */
  kind: string;
  status: string;
  progress: number;
  message?: string;
  currentStage: string;
  scenesTotal: number;
  scenesDone: number;
  errorCode?: string;
  errorMessage?: string;
  warnings: string[];
  hasOutput: boolean;
  outputDurationSeconds?: number;
  createdAt: string;
  completedAt?: string;
}

export interface RendererStatus {
  available: boolean;
  version?: string;
  unavailableReason?: string;
  burnedSubtitles: boolean;
  kenBurns: boolean;
  transitions: boolean;
}

export interface TranscriptSourceStatus {
  kind: string;
  available: boolean;
  unavailableReason?: string;
  toolVersion?: string;
  requiresAttestation: boolean;
}

export interface IngestCapabilities {
  defaultSource: string;
  mediaDownloadAllowed: boolean;
  sources: TranscriptSourceStatus[];
}

/** Terminal statuses; polling stops on any of these. */
export const TERMINAL_JOB_STATUSES = [
  'Completed',
  'CompletedWithWarnings',
  'Failed',
  'Cancelled',
] as const;

export function isTerminal(status: string): boolean {
  return (TERMINAL_JOB_STATUSES as readonly string[]).includes(status);
}


// --- clip studio: several finished clips joined into one file -----------------

export interface Clip {
  id: string;
  name: string;
  fileSizeBytes: number;
  durationSeconds?: number;
  width?: number;
  height?: number;
  hasAudio: boolean;
}

/**
 * How one line of a pasted running order was read. Mirrors the server's ClipOrderMatch,
 * because the UI colours each line by it.
 */
export type ClipOrderMatch = 'Matched' | 'Ambiguous' | 'Unmatched' | 'Duplicate';

export interface ClipOrderLine {
  number: number;
  text: string;
  assetId?: string;
  match: ClipOrderMatch;
}

export interface ClipOrder {
  /** Always a COMPLETE ordering of what was sent, so it can be applied as-is. */
  assetIds: string[];
  lines: ClipOrderLine[];
  /** Clips the text never named. They are kept at the end rather than dropped. */
  appendedAssetIds: string[];
  isExact: boolean;
}

/** The clip screen's data and its server-side limits in one payload. */
export interface ClipStudio {
  clips: Clip[];
  logoCandidates: Asset[];
  musicCandidates: Asset[];
  defaultWatermarkText?: string;
  maxClips: number;
  maxClipUploadBytes: number;
  rendererAvailable: boolean;
  unavailableReason?: string;
  textWatermarkAvailable: boolean;
  logoWatermarkAvailable: boolean;
  transitionsAvailable: boolean;
  blurredBackdropAvailable: boolean;
}

export type WatermarkKind = 'None' | 'Text' | 'Logo';

/**
 * Note what is missing: there is no centre position. A watermark over the middle of the
 * frame covers what the viewer came to see, so the option does not exist to be chosen.
 */
export const WATERMARK_POSITIONS = [
  'TopRight', 'TopLeft', 'TopCenter', 'BottomRight', 'BottomLeft', 'BottomCenter',
] as const;

export type WatermarkPosition = (typeof WATERMARK_POSITIONS)[number];

export interface WatermarkBody {
  kind: WatermarkKind;
  text?: string | null;
  logoAssetId?: string | null;
  position: WatermarkPosition;
  opacity: number;
  heightFraction: number;
  marginFraction: number;
  colorHex?: string | null;
  backplateOpacity: number;
}

export const CLIP_FITS = ['Contain', 'Cover', 'BlurredBackdrop'] as const;

export type ClipFit = (typeof CLIP_FITS)[number];

export interface ClipMergeBody {
  assetIds: string[];
  fit: ClipFit;
  transition: string;
  transitionSeconds: number;
  muteClipAudio: boolean;
  backgroundMusicAssetId?: string | null;
  backgroundMusicVolume: number;
  watermark: WatermarkBody;
}
// --- option lists, kept beside the models so a select and its API value cannot drift ---

export const BACKGROUND_EFFECTS = [
  'None', 'ZoomIn', 'ZoomOut', 'PanLeft', 'PanRight', 'PanUp', 'PanDown',
] as const;

export const EASINGS = ['Linear', 'EaseInOut'] as const;

export const TRANSITIONS = [
  'None', 'Fade', 'Dissolve', 'WipeLeft', 'WipeRight',
  'SlideLeft', 'SlideRight', 'CircleOpen', 'CircleClose',
] as const;

export const ANCHORS = [
  'BottomLeft', 'BottomCenter', 'BottomRight', 'Center', 'CenterLeft', 'CenterRight',
] as const;

export const ENTRANCES = [
  'None', 'FadeIn', 'SlideFromLeft', 'SlideFromRight', 'SlideFromBottom',
] as const;

export const DISTRIBUTION_INTENTS = ['Personal', 'Public', 'Monetized'] as const;

/** Canvas presets, so the common shapes need no arithmetic from the user. */
export const CANVAS_PRESETS = [
  { label: 'Landscape 1080p', width: 1920, height: 1080 },
  { label: 'Landscape 720p', width: 1280, height: 720 },
  { label: 'Vertical 1080x1920', width: 1080, height: 1920 },
  { label: 'Square 1080', width: 1080, height: 1080 },
] as const;

// --- bundle import (the no-AI path: one .zip with sheets, images and audio) ---

export type ImportAction = 'Create' | 'Update' | 'Conflict' | 'Unchanged';

export interface ImportRowPlan {
  sheet: string;
  rowNumber: number;
  key: string;
  action: ImportAction;
  detail: string;
}

export interface ImportSheetPlan {
  sheet: string;
  create: number;
  update: number;
  conflict: number;
  unchanged: number;
  rows: ImportRowPlan[];
}

/** A cell that could not be read, addressed the way the spreadsheet shows it. */
export interface WorkbookCellError {
  sheet: string;
  row: number;
  column: string | null;
  code: string;
  message: string;
}

export interface BundlePreview {
  previewToken: string;
  expiresAtUtc: string;
  sheets: ImportSheetPlan[];
  errors: WorkbookCellError[];
  warnings: string[];
  mediaFilesUsed: number;
  mediaFilesUnused: number;
  hasTranscript: boolean;
  canApply: boolean;
}

export interface BundleApplyBody {
  previewToken: string;
  overwriteUserEdits: boolean;
  removeMissingScenes: boolean;
}

export interface BundleImportResult {
  charactersCreated: number;
  charactersUpdated: number;
  scenesCreated: number;
  scenesUpdated: number;
  scenesRemoved: number;
  assetsCreated: number;
  dialogueLines: number;
  projectUpdated: boolean;
  warnings: string[];
}

// --- AI provider status, for the admin screen ---

export interface AiCapabilityStatus {
  capability: string;
  providerId: string | null;
  model: string | null;
  available: boolean;
  reason: string;
  dailyRemaining: number | null;
  chain: string[];
}

export interface AiCapabilities {
  capabilities: AiCapabilityStatus[];
}

// --- running the server -----------------------------------------------------------------

/** Whether this browser may change the server's settings, and why not when it may not. */
export interface AdminAccess {
  mode: 'Disabled' | 'LocalOnly' | 'Jwt';
  canAdminister: boolean;
  explanation: string;
}

/**
 * What the console is allowed to know about an installed key: enough to prove which key is
 * in place, never enough to use it. There is deliberately no field a key could arrive in.
 */
export interface AdminKey {
  configured: boolean;
  source: 'None' | 'Database' | 'Configuration';
  masked: string;
  fingerprint: string | null;
  createdAt: string | null;
  rotatedAt: string | null;
}

export interface AdminProvider {
  id: string;
  displayName: string;
  capability: string;
  family: string;
  runsLocally: boolean;
  requiresApiKey: boolean;
  freeTierNote: string;
  keyUrl: string | null;

  enabled: boolean;
  model: string | null;
  baseUrl: string | null;
  dailyRequestLimit: number | null;
  monthlyRequestLimit: number | null;
  timeoutSeconds: number | null;
  supportsJsonMode: boolean;

  /** True once it has been saved here, at which point these values beat appsettings.json. */
  managedHere: boolean;

  key: AdminKey;
  ready: boolean;
  readyReason: string;
  dailyRemaining: number | null;
  chainPosition: number | null;

  /** A provider that is a program on this machine. Its paths are shown, never editable. */
  needsExecutable: boolean;
  executableConfigured: boolean;
  modelFolderConfigured: boolean;

  defaultBaseUrl: string | null;
  defaultModel: string | null;
}

export interface AdminChain {
  capability: string;
  providerIds: string[];
  managedHere: boolean;
  candidates: string[];
}

export interface AdminProviders {
  providers: AdminProvider[];
  chains: AdminChain[];
  hostAllowlist: string[];
  encryptionConfigured: boolean;
}

export interface AdminProviderTest {
  providerId: string;
  healthy: boolean;
  reason: string | null;
}

export interface AdminProviderBody {
  enabled: boolean;
  model: string | null;
  baseUrl: string | null;
  dailyRequestLimit: number | null;
  monthlyRequestLimit: number | null;
  timeoutSeconds: number | null;
  supportsJsonMode: boolean | null;
}

export interface AdminUsageRow {
  day: string;
  providerId: string;
  capability: string;
  requests: number;
  units: number;
  cacheHits: number;
  failures: number;
}

export interface AdminUsage {
  fromDay: string;
  toDay: string;
  rows: AdminUsageRow[];
}

export type HealthState = 'Ok' | 'Degraded' | 'Missing' | 'Failed';

export interface AdminHealthProbe {
  key: string;
  displayName: string;
  state: HealthState;
  detail: string | null;
  advice: string | null;
  required: boolean;
}

export interface AdminHealth {
  healthy: boolean;
  checkedAtUtc: string;
  probes: AdminHealthProbe[];
}

export interface AdminJob {
  id: string;
  projectId: string;
  projectName: string | null;
  status: string;
  progress: number;
  message: string | null;
  stage: string;
  scenesTotal: number;
  scenesDone: number;
  attempts: number;
  errorCode: string | null;
  errorMessage: string | null;
  hasOutput: boolean;
  isTerminal: boolean;
  createdAt: string;
  completedAt: string | null;
}

export interface AdminAuditEntry {
  action: string;
  target: string | null;
  actorUserId: string | null;
  remoteAddress: string | null;
  before: string | null;
  after: string | null;
  atUtc: string;
}
