using AnimStudio.Domain.Transcripts;

namespace AnimStudio.Application.Transcripts.Parsing;

public enum SubtitleFormat { Unknown = 0, WebVtt = 1, SubRip = 2, PlainText = 3 }

public sealed record SubtitleParseResult
{
    public required SubtitleFormat Format { get; init; }
    public required IReadOnlyList<TranscriptCue> Cues { get; init; }
    public required TimingSource TimingSource { get; init; }
    public bool IsAutoGenerated { get; init; }
    public IReadOnlyList<string> Warnings { get; init; } = [];
}

/// <summary>Raised for input that cannot yield any usable cue.</summary>
public sealed class SubtitleParseException(string code, string message) : Exception(message)
{
    /// <summary>Machine-readable reason, returned to the client instead of a stack trace.</summary>
    public string Code { get; } = code;
}
