using System.Text;
using System.Text.RegularExpressions;
using AnimStudio.Domain.Transcripts;

namespace AnimStudio.Application.Transcripts.Parsing;

public interface ISubtitleParser
{
    SubtitleParseResult Parse(string content, SubtitleFormat? hint = null);
}

/// <summary>
/// Parses WebVTT, SubRip and plain text into normalized cues.
/// <para>
/// Pure text in, cues out - no I/O, no configuration lookups, no clock. That is what makes
/// the whole edge-case surface (BOMs, CRLF, rolling auto-captions, half-second fractions)
/// testable with golden-file fixtures and no external tooling.
/// </para>
/// </summary>
public sealed partial class SubtitleParser(ParsingOptions options) : ISubtitleParser
{
    [GeneratedRegex(@"^\d+$", RegexOptions.CultureInvariant | RegexOptions.NonBacktracking,
        matchTimeoutMilliseconds: 500)]
    private static partial Regex SequenceNumber();

    [GeneratedRegex(@"^\s*(NOTE|STYLE|REGION)\b", RegexOptions.CultureInvariant,
        matchTimeoutMilliseconds: 500)]
    private static partial Regex VttMetadataBlock();

    public SubtitleParseResult Parse(string content, SubtitleFormat? hint = null)
    {
        ArgumentNullException.ThrowIfNull(content);

        if (content.Length > options.MaxTranscriptCharacters)
        {
            throw new SubtitleParseException("transcript-too-large",
                $"Transcript exceeds the {options.MaxTranscriptCharacters:N0} character limit.");
        }

        var text = Prepare(content);
        var format = hint ?? Sniff(text);
        var warnings = new List<string>();

        if (format == SubtitleFormat.PlainText)
        {
            var synthesized = PlainTextSegmenter.Synthesize(text, options);
            // "Name:" prefixes are the only speaker signal plain text has.
            synthesized = SpeakerPrefixDetector.Apply(synthesized);
            warnings.Add("No timings found in the source; cue times were estimated from a reading rate. "
                       + "Audio slicing is unavailable for this transcript.");
            var normalizedPlain = CueNormalizer.Normalize(synthesized, options, warnings);
            return new SubtitleParseResult
            {
                Format = SubtitleFormat.PlainText,
                Cues = normalizedPlain,
                TimingSource = TimingSource.Synthesized,
                Warnings = warnings
            };
        }

        var raw = format == SubtitleFormat.SubRip
            ? ScanSubRip(text)
            : ScanWebVtt(text);

        if (raw.Count == 0)
        {
            throw new SubtitleParseException("unparseable-subtitle",
                "No subtitle cues could be read from this file.");
        }

        if (raw.Count > options.MaxCueCount)
        {
            throw new SubtitleParseException("too-many-cues",
                $"Transcript exceeds the {options.MaxCueCount:N0} cue limit.");
        }

        // Auto-caption handling. Prefer rebuilding from per-word timestamps, which yields
        // better timings than the source cues; otherwise fall back to suffix de-duplication.
        var isAutoGenerated = false;
        if (AutoCaptionWordTimeline.IsApplicable(raw))
        {
            raw = AutoCaptionWordTimeline.Rebuild(raw, options.WordGapBreakMs, options.MaxCueChars);
            isAutoGenerated = true;
            warnings.Add("Rebuilt cues from auto-caption word timings.");
        }
        else if (AutoCaptionWordTimeline.LooksRolling(raw))
        {
            raw = RollingSuffixDeduplicator.Deduplicate(raw);
            isAutoGenerated = true;
            warnings.Add("Removed repeated text from rolling auto-captions.");
        }

        // Applied after de-duplication so a rolling caption's repeated prefix is not
        // counted twice, and before normalization, which is what reads Speaker.
        raw = SpeakerPrefixDetector.Apply(raw);

        var cues = CueNormalizer.Normalize(raw, options, warnings);
        if (cues.Count == 0)
        {
            throw new SubtitleParseException("unparseable-subtitle",
                "The subtitle file contained no usable dialogue.");
        }

        return new SubtitleParseResult
        {
            Format = format,
            Cues = cues,
            TimingSource = TimingSource.Real,
            IsAutoGenerated = isAutoGenerated,
            Warnings = warnings
        };
    }

    /// <summary>
    /// Strips byte-order marks and normalizes line endings.
    /// <para>
    /// The BOM is stripped in a loop, not once: a file re-saved by some editors carries a
    /// doubled BOM, and "﻿WEBVTT" fails header detection - the classic
    /// works-on-my-machine VTT bug. CRLF is normalized before any block scanning because
    /// VTT's "a blank line ends a cue" rule breaks on a stray carriage return.
    /// </para>
    /// </summary>
    private static string Prepare(string content)
    {
        var text = content.Replace("\r\n", "\n").Replace('\r', '\n');
        var start = 0;
        while (start < text.Length && text[start] == '﻿') start++;
        return start > 0 ? text[start..] : text;
    }

    private static SubtitleFormat Sniff(string text)
    {
        var lines = text.Split('\n');
        var first = lines.FirstOrDefault(l => l.Trim().Length > 0)?.Trim() ?? string.Empty;

        if (first.StartsWith("WEBVTT", StringComparison.OrdinalIgnoreCase))
            return SubtitleFormat.WebVtt;

        for (var i = 0; i < lines.Length - 1; i++)
        {
            if (!SequenceNumber().IsMatch(lines[i].Trim())) continue;
            var next = lines[i + 1];
            if (next.Contains("-->", StringComparison.Ordinal) && next.Contains(','))
                return SubtitleFormat.SubRip;
        }

        // Lenient: a file with arrows but no recognizable header still parses as VTT.
        return text.Contains("-->", StringComparison.Ordinal)
            ? SubtitleFormat.WebVtt
            : SubtitleFormat.PlainText;
    }

    private static List<RawCue> ScanWebVtt(string text)
    {
        var cues = new List<RawCue>();
        var blocks = text.Split("\n\n", StringSplitOptions.None);
        var index = 0;

        foreach (var block in blocks)
        {
            if (block.Trim().Length == 0) continue;

            // Skip the header and metadata blocks entirely.
            if (block.TrimStart().StartsWith("WEBVTT", StringComparison.OrdinalIgnoreCase)) continue;
            if (VttMetadataBlock().IsMatch(block)) continue;

            var lines = block.Split('\n');
            var timingLine = -1;
            for (var i = 0; i < lines.Length; i++)
            {
                if (lines[i].Contains("-->", StringComparison.Ordinal)) { timingLine = i; break; }
            }

            // No timing line: an optional cue identifier with no timing is not a cue.
            if (timingLine < 0) continue;
            if (!TimecodeParser.TryParseCueLine(lines[timingLine], out var start, out var end)) continue;

            var payload = string.Join('\n', lines.Skip(timingLine + 1));
            if (payload.Trim().Length == 0) continue;

            cues.Add(new RawCue(index++, start, end, payload)
            {
                Speaker = InlineTagStripper.ExtractVoiceSpeaker(payload)
            });
        }

        return cues;
    }

    private static List<RawCue> ScanSubRip(string text)
    {
        var cues = new List<RawCue>();
        var blocks = text.Split("\n\n", StringSplitOptions.None);
        var index = 0;

        foreach (var block in blocks)
        {
            if (block.Trim().Length == 0) continue;

            var lines = block.Split('\n').ToList();
            // Drop the leading sequence number if present; it is advisory, not authoritative.
            if (lines.Count > 0 && SequenceNumber().IsMatch(lines[0].Trim())) lines.RemoveAt(0);
            if (lines.Count < 2) continue;

            if (!TimecodeParser.TryParseCueLine(lines[0], out var start, out var end)) continue;

            var payload = string.Join('\n', lines.Skip(1));
            if (payload.Trim().Length == 0) continue;

            cues.Add(new RawCue(index++, start, end, payload));
        }

        return cues;
    }
}
