using AnimStudio.Application.LiveStreams;

namespace AnimStudio.Application.Tests.LiveStreams;

public class LiveStreamValidatorTests
{
    private static readonly string[] Destinations = ["youtube"];

    [Theory]
    [InlineData("abcd-efgh-ijkl-mnop-qrst")]
    [InlineData("x7k2-9mq4-ab12-zz90-4f5g")]
    [InlineData("Ab_cd1234")]
    public void Accepts_keys_shaped_like_real_ones(string key) =>
        Assert.Null(LiveStreamValidator.ValidateStreamKey(key));

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("short")]
    // Anything that could re-point the ingest URL once the key is appended to it.
    [InlineData("abcd-efgh/../other-app")]
    [InlineData("abcd-efgh?backup=1")]
    [InlineData("user@evil.example")]
    [InlineData("abcd efgh ijkl mnop")]
    [InlineData("-leading-dash-key")]
    public void Refuses_anything_else(string? key) =>
        Assert.NotNull(LiveStreamValidator.ValidateStreamKey(key));

    [Fact]
    public void Refuses_a_key_longer_than_any_real_one() =>
        Assert.NotNull(LiveStreamValidator.ValidateStreamKey(new string('a', 129)));

    private static readonly LiveStreamSettings Valid = new() { RightsConfirmed = true };

    [Fact]
    public void Default_settings_with_rights_confirmed_are_valid() =>
        Assert.Null(LiveStreamValidator.ValidateSettings(Valid, Destinations));

    [Fact]
    public void Nothing_streams_without_the_rights_confirmation() =>
        Assert.NotNull(LiveStreamValidator.ValidateSettings(new LiveStreamSettings(), Destinations));

    [Fact]
    public void Refuses_a_destination_the_server_did_not_configure() =>
        Assert.NotNull(LiveStreamValidator.ValidateSettings(
            Valid with { Destination = "rtmps://attacker.example/live" }, Destinations));

    [Theory]
    [InlineData(-1)]
    [InlineData(LiveStreamValidator.MaxLoops + 1)]
    public void Refuses_out_of_range_loop_counts(int loops) =>
        Assert.NotNull(LiveStreamValidator.ValidateSettings(Valid with { Loops = loops }, Destinations));

    [Fact]
    public void Refuses_undefined_enum_values() =>
        Assert.NotNull(LiveStreamValidator.ValidateSettings(
            Valid with { Quality = (LiveStreamQuality)42 }, Destinations));

    [Fact]
    public void Refuses_a_label_with_line_breaks() =>
        Assert.NotNull(LiveStreamValidator.ValidateSettings(Valid with { Label = "a\nb" }, Destinations));

    // ------------------------------------------------------------------ playlist

    private static LiveStreamItemRequest Upload(string field = "file0") =>
        new() { Source = LiveStreamItemSource.Upload, FileField = field };

    [Fact]
    public void A_mixed_playlist_is_valid()
    {
        var check = LiveStreamValidator.ValidateItems(
        [
            Upload("file0") with { CoverField = "cover0" },
            new() { Source = LiveStreamItemSource.Render, RenderJobId = "665f1c2ab4d3e9a1f0c4b7d2" },
            new() { Source = LiveStreamItemSource.Asset, AssetId = "a1", CoverAssetId = "img_2" },
            new() { Source = LiveStreamItemSource.Url, Url = "https://youtu.be/dQw4w9WgXcQ" },
            new() { Source = LiveStreamItemSource.ReleaseKit, ReleaseKitId = "0f8e7d6c5b4a39281706f5e4d3c2b1a0" },
        ]);

        Assert.True(check.IsValid, check.Error);
        Assert.Null(check.CanonicalUrls[0]);
        Assert.StartsWith("https://", check.CanonicalUrls[3]);
    }

    [Fact]
    public void An_empty_playlist_is_refused() =>
        Assert.False(LiveStreamValidator.ValidateItems([]).IsValid);

    [Fact]
    public void A_playlist_over_the_limit_is_refused() =>
        Assert.False(LiveStreamValidator.ValidateItems(
            Enumerable.Range(0, LiveStreamValidator.MaxItems + 1).Select(i => Upload($"file{i}")).ToList()).IsValid);

    [Theory]
    // Part names are generated by the client from a fixed pattern; anything else could
    // be a path or collide with the settings fields.
    [InlineData("settings")]
    [InlineData("../file0")]
    [InlineData("file100")]
    [InlineData("cover0")]
    public void Upload_fields_must_be_generated_names(string field) =>
        Assert.False(LiveStreamValidator.ValidateItems([Upload(field)]).IsValid);

    [Fact]
    public void Two_items_cannot_share_a_file() =>
        Assert.False(LiveStreamValidator.ValidateItems([Upload("file0"), Upload("file0")]).IsValid);

    [Theory]
    [InlineData("../../etc/passwd")]
    [InlineData("a/b")]
    [InlineData("")]
    public void Ids_that_could_be_paths_are_refused(string id) =>
        Assert.False(LiveStreamValidator.ValidateItems(
            [new() { Source = LiveStreamItemSource.Render, RenderJobId = id }]).IsValid);

    [Theory]
    [InlineData("http://youtu.be/dQw4w9WgXcQ")]          // not TLS
    [InlineData("https://attacker.example/video.mp4")]  // not an allowed host
    [InlineData("file:///c:/secret.mp4")]
    public void Links_must_be_https_on_a_supported_site(string url)
    {
        var check = LiveStreamValidator.ValidateItems([new() { Source = LiveStreamItemSource.Url, Url = url }]);
        Assert.False(check.IsValid);
        Assert.Equal(0, check.ItemIndex);
    }

    [Fact]
    public void The_failing_item_is_named() =>
        Assert.Equal(1, LiveStreamValidator.ValidateItems(
            [Upload(), new() { Source = LiveStreamItemSource.Asset }]).ItemIndex);

    [Fact]
    public void Redact_removes_every_copy_of_the_key()
    {
        const string key = "abcd-efgh-ijkl-mnop-qrst";
        var stderr = $"Output #0, flv, to 'rtmps://a.rtmps.youtube.com/live2/{key}':\n"
                     + $"[rtmps @ 0x1] rtmps://a.rtmps.youtube.com/live2/{key}: I/O error";

        var redacted = LiveStreamValidator.Redact(stderr, key);

        Assert.DoesNotContain(key, redacted);
        Assert.Contains(LiveStreamValidator.KeyMask, redacted);
        Assert.Contains("I/O error", redacted);
    }
}
