using System.Security.Cryptography;
using System.Text;
using AnimStudio.Application.Abstractions.Storage;
using AnimStudio.Application.Abstractions.Transcripts;
using AnimStudio.Application.Options;
using AnimStudio.Application.Transcripts.Parsing;
using AnimStudio.Domain.Transcripts;
using Microsoft.Extensions.Options;

namespace AnimStudio.Infrastructure.Ingest;

/// <summary>
/// Pasted transcript text. Always available - no binary, no network, no configuration -
/// which is what makes it a safe default and keeps the feature working on a bare checkout.
/// </summary>
public sealed class PastedTextTranscriptSource(ISubtitleParser parser) : ITranscriptSource
{
    public TranscriptSourceKind Kind => TranscriptSourceKind.PastedText;

    public Task<TranscriptSourceAvailability> ProbeAsync(CancellationToken ct) =>
        Task.FromResult(new TranscriptSourceAvailability(true));

    public Task<TranscriptFetchResult> FetchAsync(TranscriptFetchRequest request, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(request.RawText))
            throw new TranscriptIngestException("text-required", "Paste a transcript to continue.");

        var parsed = parser.Parse(request.RawText);

        return Task.FromResult(new TranscriptFetchResult
        {
            Cues = parsed.Cues,
            TimingSource = parsed.TimingSource,
            IsAutoGenerated = false,
            Warnings = parsed.Warnings
        });
    }
}

/// <summary>
/// An uploaded SRT or WebVTT file. Also always available.
/// </summary>
public sealed class UploadedSubtitleTranscriptSource(
    ISubtitleParser parser,
    IObjectStore store) : ITranscriptSource
{
    public TranscriptSourceKind Kind => TranscriptSourceKind.SubtitleFile;

    public Task<TranscriptSourceAvailability> ProbeAsync(CancellationToken ct) =>
        Task.FromResult(new TranscriptSourceAvailability(true));

    public async Task<TranscriptFetchResult> FetchAsync(
        TranscriptFetchRequest request, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(request.ArtifactObjectKey))
            throw new TranscriptIngestException("file-required", "Upload a subtitle file to continue.");

        await using var stream = await store.OpenAsync(request.ArtifactObjectKey, ct).ConfigureAwait(false)
            ?? throw new TranscriptIngestException("file-missing", "The uploaded file could not be found.");

        // Detect BOMs while decoding; the parser strips any that survive.
        using var reader = new StreamReader(stream, new UTF8Encoding(false),
            detectEncodingFromByteOrderMarks: true);
        var content = await reader.ReadToEndAsync(ct).ConfigureAwait(false);

        var parsed = parser.Parse(content);

        return new TranscriptFetchResult
        {
            Cues = parsed.Cues,
            TimingSource = parsed.TimingSource,
            IsAutoGenerated = parsed.IsAutoGenerated,
            RawArtifactObjectKey = request.ArtifactObjectKey,
            RawArtifactSha256 = Sha256(content),
            Warnings = parsed.Warnings
        };
    }

    internal static string Sha256(string content) =>
        Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(content)));
}

/// <summary>
/// YouTube captions via yt-dlp. Unlike the other two this needs an external binary and a
/// configuration flag, so it reports itself unavailable rather than throwing at request
/// time - and a break in yt-dlp degrades this one path instead of the product.
/// </summary>
public sealed class YouTubeCaptionsTranscriptSource(
    ISubtitleParser parser,
    YtDlpCaptionDownloader downloader,
    IObjectStore store,
    IOptions<IngestOptions> options) : ITranscriptSource
{
    private readonly IngestOptions _options = options.Value;

    public TranscriptSourceKind Kind => TranscriptSourceKind.YouTubeCaptions;

    public async Task<TranscriptSourceAvailability> ProbeAsync(CancellationToken ct)
    {
        if (!_options.AllowUrlIngest)
            return new TranscriptSourceAvailability(false, "url-ingest-disabled");

        if (!_options.YtDlp.Enabled)
            return new TranscriptSourceAvailability(false, "yt-dlp-disabled");

        var version = await downloader.GetVersionAsync(ct).ConfigureAwait(false);
        return version is null
            ? new TranscriptSourceAvailability(false, "yt-dlp-not-installed")
            : new TranscriptSourceAvailability(true, ToolVersion: version,
                RequiresAttestation: _options.RequireRightsAttestation);
    }

    public async Task<TranscriptFetchResult> FetchAsync(
        TranscriptFetchRequest request, CancellationToken ct)
    {
        var availability = await ProbeAsync(ct).ConfigureAwait(false);
        if (!availability.IsAvailable)
        {
            // Never silently fall back to another source: that teaches the wrong mental
            // model about what the server just did.
            throw new TranscriptIngestException(
                availability.UnavailableReasonCode ?? "url-ingest-unavailable",
                "Importing from a URL is not enabled on this server.");
        }

        if (request.CanonicalUrl is null)
            throw new TranscriptIngestException("url-required", "A video URL is required.");

        // Requesting media without the operator gate is refused outright rather than
        // quietly downgraded to captions.
        if (request.IncludeMedia && !_options.AllowMediaDownload)
            throw new TranscriptIngestException("media-download-disabled",
                "Downloading media from a URL is not enabled on this server.");

        var download = await downloader.DownloadAsync(request.CanonicalUrl, ct).ConfigureAwait(false);
        var parsed = parser.Parse(download.Content, SubtitleFormat.WebVtt);

        string? artifactKey = null;
        if (_options.RetainRawCaptionArtifact)
        {
            // Keeping the raw file makes a later parsing complaint answerable.
            artifactKey = $"projects/{request.ProjectId}/ingest/{request.IngestId}/captions.vtt";
            var bytes = Encoding.UTF8.GetBytes(download.Content);
            using var buffer = new MemoryStream(bytes);
            await store.SaveAsync(artifactKey, buffer, "text/vtt", ct).ConfigureAwait(false);
        }

        return new TranscriptFetchResult
        {
            Cues = parsed.Cues,
            TimingSource = parsed.TimingSource,
            Language = download.Language,
            IsAutoGenerated = download.IsAutoGenerated || parsed.IsAutoGenerated,
            RawArtifactObjectKey = artifactKey,
            RawArtifactSha256 = UploadedSubtitleTranscriptSource.Sha256(download.Content),
            SourceVideoId = download.VideoId,
            SourceChannelKey = download.ChannelKey,
            SourceTitle = download.Title,
            Warnings = parsed.Warnings,
            ToolName = "yt-dlp",
            ToolVersion = availability.ToolVersion
        };
    }
}

/// <summary>Resolves a source kind to its implementation.</summary>
public sealed class TranscriptSourceSelector(IEnumerable<ITranscriptSource> sources)
{
    private readonly Dictionary<TranscriptSourceKind, ITranscriptSource> _sources =
        sources.ToDictionary(s => s.Kind);

    public ITranscriptSource Resolve(TranscriptSourceKind kind) =>
        _sources.TryGetValue(kind, out var source)
            ? source
            : throw new TranscriptIngestException("source-not-supported",
                "That transcript source is not supported.");

    public IReadOnlyCollection<ITranscriptSource> All => _sources.Values;
}
