using System.Diagnostics;
using System.Text;
using AnimStudio.Application.Abstractions.Transcripts;
using AnimStudio.Application.Options;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace AnimStudio.Infrastructure.Ingest;

public sealed record CaptionDownload(
    string Content, string? Language, bool IsAutoGenerated,
    string? VideoId, string? ChannelKey, string? Title, string? ToolVersion);

/// <summary>
/// Fetches captions for a single YouTube video via yt-dlp.
/// <para>
/// Captions-only by construction, not by convention: the argument vector is built from a
/// fixed template in which <c>--skip-download</c> is always present and there is no code
/// path that omits it. Media download is a different handler entirely, behind its own
/// configuration gate.
/// </para>
/// </summary>
public sealed class YtDlpCaptionDownloader(
    IOptions<IngestOptions> options,
    ILogger<YtDlpCaptionDownloader> logger)
{
    private readonly IngestOptions _options = options.Value;

    public async Task<string?> GetVersionAsync(CancellationToken ct)
    {
        try
        {
            var result = await RunAsync(["--version"], Path.GetTempPath(), ct).ConfigureAwait(false);
            return result.ExitCode == 0 ? result.StdOut.Trim() : null;
        }
        catch (Exception ex) when (ex is System.ComponentModel.Win32Exception or FileNotFoundException)
        {
            return null;
        }
    }

    public async Task<CaptionDownload> DownloadAsync(Uri canonicalUrl, CancellationToken ct)
    {
        var workDirectory = Path.Combine(Path.GetTempPath(), "animstudio-ingest",
            Guid.NewGuid().ToString("n"));
        Directory.CreateDirectory(workDirectory);

        try
        {
            var languages = string.Join(',', _options.PreferredCaptionLanguages);
            var stem = Guid.NewGuid().ToString("n");

            // Fixed template. Note --skip-download and --no-playlist; the URL is passed
            // last, after "--", so it can never be read as an option.
            string[] arguments =
            [
                "--skip-download",
                "--write-subs",
                "--write-auto-subs",
                "--sub-langs", languages,
                "--sub-format", "vtt",
                "--no-playlist",
                "--no-warnings",
                "--no-progress",
                "--restrict-filenames",
                "--no-part",
                "--no-continue",
                "--print-to-file", "%(id)s\t%(channel_id)s\t%(title)s", "meta.txt",
                "-o", stem,
                "--",
                canonicalUrl.AbsoluteUri
            ];

            var result = await RunAsync(arguments, workDirectory, ct).ConfigureAwait(false);

            if (result.ExitCode != 0)
            {
                logger.LogWarning("yt-dlp exited with {ExitCode} fetching captions.", result.ExitCode);
                throw new TranscriptIngestException("captions-unavailable",
                    "Captions could not be fetched for that video.");
            }

            var subtitleFile = Directory
                .EnumerateFiles(workDirectory, "*.vtt", SearchOption.TopDirectoryOnly)
                .OrderBy(PreferManualOverAuto)
                .FirstOrDefault();

            if (subtitleFile is null)
                throw new TranscriptIngestException("no-captions",
                    "That video has no captions available to import.");

            var content = await File.ReadAllTextAsync(subtitleFile, ct).ConfigureAwait(false);
            var isAuto = Path.GetFileName(subtitleFile).Contains(".auto.", StringComparison.OrdinalIgnoreCase)
                         || subtitleFile.Contains("auto", StringComparison.OrdinalIgnoreCase);

            var (videoId, channelKey, title) = ReadMetadata(workDirectory);

            return new CaptionDownload(
                content, ExtractLanguage(subtitleFile), isAuto,
                videoId, channelKey, title, null);
        }
        finally
        {
            TryDelete(workDirectory);
        }
    }

    /// <summary>Manual captions are better than auto-generated ones, so sort them first.</summary>
    private static int PreferManualOverAuto(string path) =>
        path.Contains("auto", StringComparison.OrdinalIgnoreCase) ? 1 : 0;

    private static string? ExtractLanguage(string path)
    {
        // yt-dlp names files "<stem>.<lang>.vtt".
        var parts = Path.GetFileName(path).Split('.');
        return parts.Length >= 3 ? parts[^2] : null;
    }

    private static (string? VideoId, string? ChannelKey, string? Title) ReadMetadata(string directory)
    {
        var path = Path.Combine(directory, "meta.txt");
        if (!File.Exists(path)) return (null, null, null);

        var line = File.ReadLines(path).FirstOrDefault();
        if (string.IsNullOrWhiteSpace(line)) return (null, null, null);

        var fields = line.Split('\t');
        return (
            fields.Length > 0 ? Nullify(fields[0]) : null,
            fields.Length > 1 ? Nullify(fields[1]) : null,
            fields.Length > 2 ? Nullify(fields[2]) : null);

        static string? Nullify(string value) =>
            string.IsNullOrWhiteSpace(value) || value == "NA" ? null : value.Trim();
    }

    private async Task<(int ExitCode, string StdOut, string StdErr)> RunAsync(
        string[] arguments, string workingDirectory, CancellationToken ct)
    {
        var startInfo = new ProcessStartInfo
        {
            FileName = _options.YtDlp.ExecutablePath,
            WorkingDirectory = workingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            RedirectStandardInput = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        // ArgumentList, never a joined string: no shell is involved, so a hostile URL
        // cannot inject an extra option or command.
        foreach (var argument in arguments) startInfo.ArgumentList.Add(argument);

        using var process = new Process { StartInfo = startInfo };
        process.Start();
        process.StandardInput.Close();

        using var timeout = CancellationTokenSource.CreateLinkedTokenSource(ct);
        timeout.CancelAfter(TimeSpan.FromSeconds(_options.YtDlp.TimeoutSeconds));

        // Drained concurrently, and capped: a hostile or broken response must not be able
        // to exhaust memory.
        var stdoutTask = ReadCappedAsync(process.StandardOutput, timeout.Token);
        var stderrTask = ReadCappedAsync(process.StandardError, timeout.Token);

        try
        {
            await process.WaitForExitAsync(timeout.Token).ConfigureAwait(false);
        }
        catch (OperationCanceledException)
        {
            try { process.Kill(entireProcessTree: true); } catch { /* already gone */ }

            if (ct.IsCancellationRequested) throw;

            throw new TranscriptIngestException("captions-timeout",
                "Fetching captions took too long and was stopped.");
        }

        return (process.ExitCode,
            await stdoutTask.ConfigureAwait(false),
            await stderrTask.ConfigureAwait(false));
    }

    private async Task<string> ReadCappedAsync(StreamReader reader, CancellationToken ct)
    {
        var builder = new StringBuilder();
        var buffer = new char[8192];

        try
        {
            while (builder.Length < _options.YtDlp.MaxOutputBytes)
            {
                var read = await reader.ReadAsync(buffer, ct).ConfigureAwait(false);
                if (read == 0) break;
                builder.Append(buffer, 0, read);
            }
        }
        catch (OperationCanceledException)
        {
            // The process is being killed; whatever was captured is enough.
        }

        return builder.ToString();
    }

    private void TryDelete(string directory)
    {
        try
        {
            if (Directory.Exists(directory)) Directory.Delete(directory, recursive: true);
        }
        catch (Exception ex)
        {
            logger.LogDebug(ex, "Could not clean up the caption download directory.");
        }
    }
}
